"rest-client.environmentVariables": {
    "$shared": {
        "version": "v1",
        "prodToken": "eyJpZCI6MzEsInRpbWVzdGFtcHMiOiIxNzEyMDcyODUzIn0.ZgwolQ.H0HsL4M2hsb4wYphekMXWtCrMt0",
        "nonProdToken": "bar"
    },
    "local": {
        "version": "v2",
        "host": "localhost",
        "token": "{{$shared nonProdToken}}",
        "secretKey": "devSecret"
    },
    "production": {
        "host": "example.com",
        "token": "{{$shared prodToken}}",
        "secretKey" : "prodSecret"
    }
}

@hostname = localhost
@protocol = http
@port = 5000
@host = {{protocol}}://{{hostname}}:{{port}}
@contentType = application/json



### post
# @name Login
POST {{host}}/api/users HTTP/1.1
Content-Type: {{contentType}}

{
    "username" : "admin",
    "password" : "admin"
}

### get
#
@token = {{Login.response.body.$.token}}

GET {{host}}/products HTTP/1.1
Authorization: {{token}}

### post
# @name AddProduct
POST {{host}}/products HTTP/1.1
Content-Type: {{contentType}}
Authorization: {{token}}

{
    "name" : "truc2",
    "description": "machine",
    "price": "999"
}

### put
# @name ModifyProduct
@product_id = {{AddProduct.response.body.$.id}}
PUT {{host}}/product/{{product_id}} HTTP/1.1
Content-Type: {{contentType}}

{
    "name" : "truc2",
    "description": "machine chose",
    "price": "333"
}

### path
PATCH {{host}}/product/{{product_id}} HTTP/1.1
Content-Type: {{contentType}}

{
    "price": "555"
}

### delete
DELETE {{host}}/product/{{product_id}} HTTP/1.1
