### get 
GET http://127.0.0.1:5000/products HTTP/1.1

### post
POST http://127.0.0.1:5000/products HTTP/1.1
Content-Type: application/json

{
    "name" : "truc",
    "description": "machine",
    "price": "999"
}

### put
PUT http://127.0.0.1:5000/product/2 HTTP/1.1
Content-Type: application/json

{
    "name" : "truc",
    "description": "machine chose",
    "price": "333"
}

### path
PATCH http://127.0.0.1:5000/product/2 HTTP/1.1
Content-Type: application/json

{
    "price": "555"
}

### delete
DELETE http://127.0.0.1:5000/product/2 HTTP/1.1
